### ISSUE TITLE
[whishlist] Add desktop notifications

### ISSUE THREAD

**Issue by pmlopes** [jle64/gnome-pass-search-provider#1]
When a user selects a password and presses enter there is no feedback, maybe a notification saying that the password was copied would be interesting.

Same when pass errors out. For example the gpg key is missing, then no feedback is reported and nothing gets into the clipboard.

**Comment by jle64** [comment]
Whoah, I didn't realize there was any user of this beside me yet :)

Yeah, good points I'll look into adding some libnotify notifications with stderr output when pass exits != 0 and when a password is copied to clipboard.

**Comment by pmlopes** [comment]
I guess you can use DBus directly e.g.:

```py
                
notifications_dbus = session_bus.get_object('org.freedesktop.Notifications', '/org/freedesktop/Notifications')
notify = dbus.Interface(notifications_dbus, 'org.freedesktop.Notifications')
notify.Notify (name, 0, '', name + ' password copied.', '', '', '', 3000)
```

I'm no dbus expert or python but this gives me some hints, it probably needs some polishing specially with the messages and defaults but again i just looked at the spec for 5 minutes....

**Comment by jle64** [comment]
I've added it. Notifications seems to stay indefinitely in Gnome notifications history despite setting a 3s timeout though. Also I barely tested :)

**Comment by pmlopes** [comment]
:+1:

**Comment by pmlopes** [comment]
if you use the hints:

```py
{'transient': True}
```

then they do not stay in the history (hints is the argument before the timeout.

**Comment by pmlopes** [comment]
Also for some strange reason on my Fedora 26 notifications have a huge delay before they show up. How do you debug this?

**Comment by jle64** [comment]
I changed notifications to be transient. I have no idea why you would have a delay when notifications show up, I don't have the problem.

**Comment by pmlopes** [comment]
it seems like a deadlock on the subprocess until some timeout happens

**Comment by matze** [comment]
> Also for some strange reason on my Fedora 26 notifications have a huge delay before they show up. 

And it's **pretty** annoying as well …

**Comment by pmlopes** [comment]
I've got it working for me with this code:

```py
def send_password_to_native_clipboard(self, name):
        pass_cmd = subprocess.run(['pass', 'show', '-c', name])

        if pass_cmd.returncode:
            self.notify('Failed to copy password!', error=True)
        else:
            self.notify('Password {} copied to clipboard.'.format(name))
```

By not creating pipes from the stdin/stdout it works, but I loose the context for error messages, not optimal but works for me...

**Comment by matze** [comment]
Yes, works well but also means no GPaste support but I personally do not use that either.

**Comment by jle64** [comment]
@pmlopes : I imported your version of the function.

@matze : The problem doesn't occur with GPaste support anyway (which is why I didn't see it) as it seems to be due to the subprocess call blocking until the end of the 45 seconds before clearing the clipboard content, which isn't used in the case of GPaste.
