### ISSUE TITLE
[Request] Package for Nix or publish on extensions.gnome.org

### ISSUE THREAD

**Issue by Spass1966** [jle64/gnome-pass-search-provider#14]
NixOS is an immutable Linux-based OS that uses its own paths incompatible with the FHS.

Are there blockers from publishing this directly on extensions.gnome.org?

**Comment by jle64** [comment]
Concerning extensions.gnome.org: This doesn't count as an extension as this is made in python and runs as its own process, using dbus to communicate with gnome-shell. Extensions are different, they are made in javascript and are loaded by gnome-shell itself. Therefore, it would need a rewrite to become an extension and be able to be moved to extensions.gnome.org.

Concerning nix or other distros packaging, this is just a matter of someone being motivated to do it :wink:
