### ISSUE TITLE
Doesn't work with 3.34

### ISSUE THREAD

**Issue by nielsk** [jle64/gnome-pass-search-provider#18]
I have installed gnome 3.34 and gnome-pass-search-provider doesn't seem to work anymore. Results are just not shown.

**Comment by ftostevin** [comment]
Removing 
https://github.com/jle64/gnome-pass-search-provider/blob/f12076dc512c677542ca9fe38686444c6f485dd9/conf/org.gnome.Pass.SearchProvider.desktop#L10
makes the results appear in the search again

**Comment by jle64** [comment]
@ftostevin @nielsk I've removed the "NoDisplay=true" in the .desktop. Can you confirm that this fixes the issue (I'm not on 3.34 yet so I can't test/reproduce).

**Comment by nielsk** [comment]
I can do that but it will take a day or two since I am on vacation.

**Comment by ftostevin** [comment]
Works for me. Of course this has the downside that the desktop file also appears in the application search, where it doesn't do anything.

**Comment by nielsk** [comment]
works for me. Thanks.

**Comment by jle64** [comment]
Thanks. Closing issue then.

**Comment by francium** [comment]
@jle64 I don't think the AUR package got updated, last update was 2019-06-01

**Comment by jle64** [comment]
The AUR package always uses the latest git version, so it shouldn't need to be updated.
