### ISSUE TITLE
GPG called two times when gpaste is not installed

### ISSUE THREAD

**Issue by pietroalbini** [jle64/gnome-pass-search-provider#19]
Thanks for this great extension!

One minor annoyance I noticed with it is that when `gpaste` is not installed the extension calls `pass` (and thus `gpg`) two times. This is fine for most users, but if you have a smartcard (such as a YubiKey) that requires a physical touch to decrypt each file it gets annoying pretty fast, as you have to touch the smartcard two times each password you decrypt.

Thankfully after taking a look at the source the workaround (just installing `gpaste`) was trivial, but maybe you could check whether `gpaste` is available over DBus before choosing which method to copy the password to use?

**Comment by jle64** [comment]
Thanks for the report.

Merged #20. Should be fixed.

**Comment by pietroalbini** [comment]
Thanks :heart:
