### ISSUE TITLE
Failed to copy password on gnome40 without Gpaste

### ISSUE THREAD

**Issue by demolg** [jle64/gnome-pass-search-provider#27]

**Comment by jle64** [comment]
How can I reproduce the issue (it works fine for me on Gnome 40 on Arch Linux) ? What is your system, is there anything in the logs at the time of the error (on systemd-based systems running `journalctl --user --follow` then reproducing the error should show that), is there anything weird about your setup (use of env vars to configure pass ?) ?

**Comment by demolg** [comment]
Thanks for your suggestion. I'm on Gnome 40 on Arch Linux. run `journalctgl --user --follow` then search and select a password. Finally pop notification "Failed to copy password". The journal show:
```
Jun 15 21:13:27 Mess gnome-pass-search-provider.py[3506]: /usr/bin/pass: line 180: wl-copy: command not found
Jun 15 21:13:27 Mess gnome-pass-search-provider.py[3491]: Error: Could not copy data to the clipboard
```

I set env `PASSWORD_STORE_DIR=$XDG_DATA_HOME/pass` both in `.bashrc` and `.pam_environment`

**Comment by jnphilipp** [comment]
The new version of pass added wayland support, i.e., `wl-copy`. You need to install `wl-clipboard` at least under Arch.

**Comment by demolg** [comment]
Maybe the AUR PKGBUILD need update to add (opt)depends :)

**Comment by jnphilipp** [comment]
It's an dependency of `pass` itself, so it would need to go there.

**Comment by jle64** [comment]
Seems there is already a bug report for this : https://bugs.archlinux.org/task/71241
