### ISSUE TITLE
When gpg is updated, but old gpg-agent is still running, passwords are not copied

### ISSUE THREAD

**Issue by paper42** [jle64/gnome-pass-search-provider#30]
Instead, the first line of stderr is copied - `gpg: WARNING: server 'gpg-agent' is older than us (2.2.34 < 2.2.35)`. This message is on stderr and the password on stdout, so that could be an easy way to fix this.

**Comment by jle64** [comment]
Thanks for reporting this issue.

I pushed a fix in 2acdad5 that *should* fix it as I removed the option that put stderr in stdout. Hopefully that doesn't break anything, can't remember why it was here :shrug:.

Don't hesitate to reopen if the problem persists.

**Comment by paper42** [comment]
Thanks, I will test this with the next gpg update.
