### ISSUE TITLE
Do not ask for unlock password automatically?

### ISSUE THREAD

**Issue by infeeeee** [jle64/gnome-pass-search-provider#37]
Thank you for this! Works very well, I use this with rbw!

I have one issue:

If I just started the computer, I don't always need my passwords yet, I just want to open a program by searching for its name. Of course pinentry pops up requesting the master password as I start to search. The search is unusable until I unlock the db, the dialog will reopen after each new typed character, even if I close the prompt.

Is it possible to not show up this  dialog automatically? Maybe if the db is locked it won't try to search for a password, unless I search for `unlock` or `Pass` beforehand?

**Comment by jle64** [comment]
Thanks for reporting this, merged.
