### ISSUE TITLE
[Request] Case-insensitive search

### ISSUE THREAD

**Issue by eyal0803** [jle64/gnome-pass-search-provider#6]
I tried to understand how you code works and saw that you're using `difflib.SequenceMatcher`. I have no idea how the `ratio()` method works, but to find "ArchLinux/..." I have to type at least "archli". Notice I'm using lower-case. I can get the result faster if I type "Arc", but that's slightly less convenient.

Is there something we can do? Maybe lower (or higher?) the value you compare with `ratio()` (which is 0.5)?

**Comment by jle64** [comment]
I have modified the search function to ignore case unless uppercase letters are used in the search (smartcase). This should be better (ArchLinux shows up when typing arc).

**Comment by eyal0803** [comment]
Wow. That was fast thank you very much! Will you also update the AUR package?

**Comment by jle64** [comment]
The AUR package tracks the git repo so it is already be updated.

**Comment by eyal0803** [comment]
Sure thing. Thanks again!

**Comment by eyal0803** [comment]
Doesn't look like it's updated...

**Comment by jle64** [comment]
I just ran `pacaur -S gnome-pass-search-provider-git` and it installed the new version.

How do you upgrade ? You need to kill the old `gnome-pass-search-provider.py` process or restart your session for the new version to be used.

**Comment by eyal0803** [comment]
Check out the package's page in AUR: https://aur.archlinux.org/packages/gnome-pass-search-provider-git/

**Comment by eyal0803** [comment]
I just did `-S gnome-pass-search-provider-git` and log out and back in (`alt+F2 -> r` wasn't enough) and it works.

Is there any way I can get my AUR helper to get updates for your package? Because I did `-Syyu` and it didn't help.

Sorry for the trouble.

**Comment by jle64** [comment]
I think this depends of your AUR helper. I use pacaur (which I shouldn't do as it's deprecated but whatever) and there is a `--devel` option that I think does update -git and such packages, although I've never tried it.
